spring.config.import=optional:file:env.properties
spring.application.name=biblioteca
spring.devtools.restart.exclude=logs/**
server.port=${PORT}
# Postgres
spring.datasource.url=${JDBC_URI}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate
spring.jpa.hibernate.ddl-auto=update
# Cloudinary
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apiKey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}
# JWT CONFIG
jwt.secret=${JWT_SECRET}
# ADMIN INFO
admin.name=${ADMIN_NAME}
admin.surname=${ADMIN_SURNAME}
admin.birth=${ADMIN_BIRTH}
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
admin.phone=${ADMIN_PHONE}